require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReportTasksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ReportTask. As you add validations to ReportTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportTasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all report_tasks as @report_tasks" do
      report_task = ReportTask.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:report_tasks)).to eq([report_task])
    end
  end

  describe "GET show" do
    it "assigns the requested report_task as @report_task" do
      report_task = ReportTask.create! valid_attributes
      get :show, {:id => report_task.to_param}, valid_session
      expect(assigns(:report_task)).to eq(report_task)
    end
  end

  describe "GET new" do
    it "assigns a new report_task as @report_task" do
      get :new, {}, valid_session
      expect(assigns(:report_task)).to be_a_new(ReportTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested report_task as @report_task" do
      report_task = ReportTask.create! valid_attributes
      get :edit, {:id => report_task.to_param}, valid_session
      expect(assigns(:report_task)).to eq(report_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReportTask" do
        expect {
          post :create, {:report_task => valid_attributes}, valid_session
        }.to change(ReportTask, :count).by(1)
      end

      it "assigns a newly created report_task as @report_task" do
        post :create, {:report_task => valid_attributes}, valid_session
        expect(assigns(:report_task)).to be_a(ReportTask)
        expect(assigns(:report_task)).to be_persisted
      end

      it "redirects to the created report_task" do
        post :create, {:report_task => valid_attributes}, valid_session
        expect(response).to redirect_to(ReportTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved report_task as @report_task" do
        post :create, {:report_task => invalid_attributes}, valid_session
        expect(assigns(:report_task)).to be_a_new(ReportTask)
      end

      it "re-renders the 'new' template" do
        post :create, {:report_task => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested report_task" do
        report_task = ReportTask.create! valid_attributes
        put :update, {:id => report_task.to_param, :report_task => new_attributes}, valid_session
        report_task.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested report_task as @report_task" do
        report_task = ReportTask.create! valid_attributes
        put :update, {:id => report_task.to_param, :report_task => valid_attributes}, valid_session
        expect(assigns(:report_task)).to eq(report_task)
      end

      it "redirects to the report_task" do
        report_task = ReportTask.create! valid_attributes
        put :update, {:id => report_task.to_param, :report_task => valid_attributes}, valid_session
        expect(response).to redirect_to(report_task)
      end
    end

    describe "with invalid params" do
      it "assigns the report_task as @report_task" do
        report_task = ReportTask.create! valid_attributes
        put :update, {:id => report_task.to_param, :report_task => invalid_attributes}, valid_session
        expect(assigns(:report_task)).to eq(report_task)
      end

      it "re-renders the 'edit' template" do
        report_task = ReportTask.create! valid_attributes
        put :update, {:id => report_task.to_param, :report_task => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested report_task" do
      report_task = ReportTask.create! valid_attributes
      expect {
        delete :destroy, {:id => report_task.to_param}, valid_session
      }.to change(ReportTask, :count).by(-1)
    end

    it "redirects to the report_tasks list" do
      report_task = ReportTask.create! valid_attributes
      delete :destroy, {:id => report_task.to_param}, valid_session
      expect(response).to redirect_to(report_tasks_url)
    end
  end

end
